apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: dns-cleanup
spec:
  desiredState:
    dns-resolver:
      config:
        search: []
        server: []
    interfaces:
    - name: eth1
      state: absent
