apiVersion: console.openshift.io/v1
kind: ConsolePlugin
metadata:
  name: {{ .PluginName }}
  annotations:
    console.openshift.io/use-i18n: "true"
spec:
  displayName: 'Console Plugin for NMState'
  backend:
    type: Service
    service:
      name: {{ .PluginName }}
      namespace: {{ .PluginNamespace }}
      port: {{ .PluginPort }}
      basePath: '/'
