apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: vrf
spec:
  desiredState:
    interfaces:
    - name: vrf102
      state: up
      type: vrf
      vrf:
        port:
        - eth1
        route-table-id: 102
    - ipv4:
        address:
        - ip: 192.0.2.251
          prefix-length: 24
        dhcp: false
        enabled: true
      name: eth1
      state: up
      type: ethernet
    routes:
      config:
      - destination: 198.51.100.0/24
        metric: 150
        next-hop-address: 192.0.2.1
        next-hop-interface: eth1
        table-id: 102
  nodeSelector:
    kubernetes.io/hostname: node01
